### ISSUE TITLE
Create seeksComponent (lobby) layout

### ISSUE THREAD

**Issue by veronikaliverstam1988** [Insanelyn/Chesstastic#19]

**Comment by cmjonsson** [comment]
- Component for user who are looking for games
- Create a "loading-wheel"
- Text with "Searching for games".
- Search- and cancel button

**Comment by silfverstrom** [comment]
Routing-issues with tabs.

**Comment by cmjonsson** [comment]
Layout is donde, made a remake with a grid and the routing is accurate.
